### PR TITLE
Fix and refactor a few things

### PR DESCRIPTION
**Pull request by YacineSteeve**
## What does this PR do ?

* Change the destination of `Icon` types from `src/components/Icons/AvailableIcons.ts` to `src/libs/types/icons.type.ts`
* Add a `bash` script to shorten the `npm run icons` script.<br>
It's usage, from the root of the project directory:
```sh
npm run frontend icons
```
* Improve the `getAvailableIcons.ts` script's logs
* Other refactoring and fixing

### CODE REVIEW

**Comment by YacineSteeve** [comment]
Current dependencies on/for this PR:
* main
  * **PR #43** <a href="https://app.graphite.dev/github/pr/Frelya/react-site-editor/43" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/Frelya/react-site-editor/43?utm_source=stack-comment).

**Review by epoundor — CHANGES_REQUESTED** [review]
The props onClick doesn't have sense. An Icon is not necessary clickable

**Review by epoundor — CHANGES_REQUESTED** [review]
Icon is not a decorator. A decorator is a wrapper that adds functionality to a component.

**Comment by YacineSteeve** [comment]
> The props onClick doesn't have sense. An Icon is not necessary clickable

That's why the it's optional

**Comment by YacineSteeve** [comment]
> Icon is not a decorator. A decorator is a wrapper that adds functionality to a component.

It's a kind of wrapper, right ? Let's keep it there, it seems more suitable ^_^

**Comment by epoundor** [comment]
> > The props onClick doesn't have sense. An Icon is not necessary clickable
> 
> That's why the it's optional

 I don't see the point of putting an onClick on an icon.

**Comment by YacineSteeve** [comment]
> > > The props onClick doesn't have sense. An Icon is not necessary clickable
> > 
> > 
> > That's why the it's optional
> 
> I don't see the point of putting an onClick on an icon.

See the usage in `src/components/SidebarRight`

**Comment by epoundor** [comment]
> > I don't see the point of putting an onClick on an icon.
> 
> See the usage in `src/components/SidebarRight`. Icons are commonly clickable.

In this case, the onClick should be placed in the component where it is called. I'm not sure if you understand. You are putting it in props, but even without props, the component has a default `onClick`. If I make an analogy with `Vue.js`, you wouldn't create a component and define an emit click, right? Since it has the default `@click` handler.

**Comment by YacineSteeve** [comment]
> In this case, the onClick should be placed in the component where it is called. I'm not sure if you understand. You are putting it in props, but even without props, the component has a default `onClick`. If I make an analogy with `Vue.js`, you wouldn't create a component and define an emit click, right? Since it has the default `@click` handler.

That's where you are wrong ;)
`React` components don't have a default `onClick`, as `Vue.js` components do.
You get this error:
```
Property 'onClick' does not exist on type 'IntrinsicAttributes & CommponentProps'.
```
Instead, the components should pass these handlers as props and bind them to the rendered `html` elements.

**Review by epoundor — APPROVED** [review]

**Pull request merged**
