### PR TITLE
add `mitt`

### PR DESCRIPTION
**Pull request by epoundor**
mitt must be used to emit and handle event into the app

### CODE REVIEW

**Comment by epoundor** [comment]
@YacineSteeve can we pass a global variable with react?

**Comment by YacineSteeve** [comment]
> @YacineSteeve can we pass a global variable with react?

Like ?

**Comment by epoundor** [comment]
> > @YacineSteeve can we pass a global variable with react?
> 
> Like ?

Like vue does with app.registerGlobalProperties

**Comment by YacineSteeve** [comment]
> Like vue does with app.registerGlobalProperties

Oh I see. I haven't seen anything like that in the doc yet. 
Search for something like a `Provider`

**Review by YacineSteeve — APPROVED** [review]

**Pull request merged**
